services:
    App\Event\Subscriber\BuildDemoSchemaSubscriber:
        autoconfigure: true
        arguments:
            - 'src/Resources/schema/demo.yaml'

    App\Installer\PlatformDemoInstaller:
        autowire: true
        parent: ezplatform.installer.db_based_installer
        class: App\Installer\PlatformDemoInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
        tags:
            - { name: ezplatform.installer, type: ezplatform-demo }
