# This file contains defaults for optional parameters, which you can override in parameters.yml
parameters:
    locale_fallback: en

    # Setting for mail system, used by SwiftMailer
    env(MAILER_HOST):       127.0.0.1
    env(MAILER_USER):       ~
    env(MAILER_PASSWORD):   ~

    # One of `legacy` (default) or `solr`
    env(SEARCH_ENGINE): legacy

    # Solr root endpoint, relevant if `solr` is set as search_engine
    env(SOLR_DSN): http://localhost:8983/solr

    # root locationId used for fetching top menu sub items
    app.top_menu.location_id: 2

    # says how many random posts should be displayed on blog post page
    app.blog_post.random_posts_limit: 2

    # locationId used for contact page
    app.layout.contact_location_id: 60

    # says how many blog posts should be shown on home page
    app.home.blog_post_limit: 3

    # locationId used for fetching `blog_post` items on home page
    app.home.blog_location_id: 62

    # says how many images should be shown on home page
    app.home.gallery_image_limit: 3

    # locationId used for fetching `image` items on home page
    app.home.gallery_location_id: 61

    # number of `blog_post` items displayed per page in the blog view
    app.blog_post_list_limit: 5

    # e-mail address used for form submission
    app.contact_form.sender_email: no-reply@ez.no

    # e-mail address used as a message recipient
    app.contact_form.recipient_email: no-reply@ez.no

    # number of images displayed per page
    app.gallery.images_limit: 6

    # Settings for Cache pool, to create your own pool see cache/ folder.
    cache_pool: "default"

    cache_host: 127.0.0.1

    env(LOG_PATH): "%kernel.logs_dir%/%kernel.environment%.log"

    # Settings for Cache pool, to change add own cache service and optionally inject own arguments
    env(CACHE_POOL): "cache.app"
